//SIRVE PARA QUE PODAMOS USAR LAS VARIABLES OTRO ARCHIVO js. AL IMPORTAR DEBES USAR LLAVES Y EL NOMBRE DEBE COINCIDIR CON EL ELEMENTO IMPORTADO.
export let a=1;
export let b=2;


let c="Hola";
let d=25;

//TAMBIEN PODEMOS ENGLOBAR LAS VARIABLES EN UN OBJETO Y SÓLO IMPORTAR EN OTRO JS EL OBJETO.
export const objeto={
    c,
    d
}

// ESTE TIPO DE EXPORT ES ÙTIL CUANDO USAS SÓLO UNA FUNCIÓN, CLASE O VARIABLE POR ARCHIVO(DESDE EL QUE EXPORTAS). AL IMPORTAR NO DEBES USAR LLAVES Y, DADO QUE SÓLO PUEDES EXPORTRAS UN SÓLO ELEMENTO POR ARCHIVO CON "EXPORT DEFAULT", AL IMPORTAR PUEDES ESCOGER CUALQUIER NOMBRE.

export default a;


